### ISSUE TITLE
Arrays of tables and optional values

### ISSUE THREAD

**Issue by benjamin051000** [cptpiepmatz/static-toml#6]
The Arrays section in the docs says:
> Arrays in TOML files can have different data types for each item. However, Rust’s slices require all elements to be of the same type. This crate aims to simplify access to TOML data, so it avoids using [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html) types to handle arrays.

The data I'm working with, however, would benefit from using Options. Here's a snippet:

```toml
[[blocks]]
name = "acacia_planks"
id = 0
floor_color = [181, 101, 59]

[[blocks]]
name = "air"
id = 1

[[blocks]]
name = "andesite"
id = 2
building_corner = true

[[blocks]]
name = "blackstone"
id = 6
building_corner = true
floor_color = [22, 15, 16]

[[blocks]]
name = "brick"
id = 9
building_corner = true
wall_color = [233, 107, 57]

[[blocks]]
name = "nether_bricks"
id = 47
wall_color = [24, 13, 14]

[[blocks]]
name = "oak_leaves"
id = 49
properties.persistent = true

```

As you can see, `name` and `id` are required fields, but there are several optional fields. This is a long array of tables (128 and counting), so `static_toml!` ends up generating a 128-wide tuple. It's very cumbersome.

I'd much rather have it generate a single struct with each of these possibly-null fields as Option types. 

I understand this has intentionally not been done with this crate, but I wanted to ask if you're open to having it as a feature? If not, no worries.

Also, how much additional effort would be required to implement such a feature? Do you think there might be performance or ergonomic drawbacks (besides needing to unwrap all the Options)? 

I'm just looking to find the best way to use this crate for my weird use-case. Thanks!
